incremental: true
exclude    : [pictures, tasks, README.md]
permalink  : '/blog/:title'

sass:
  sass_dir: assets/css

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
